### ISSUE TITLE
How to Delete post?

### ISSUE THREAD

**Issue by NNN444TTT** [Tay0710/CITS3403_Project#24]
Where should the delete post 'section' be? We would need a way for people to only delete their own posts, and would this be on the forum page or maybe the profile page?

**Comment by Tay0710** [comment]
I think putting it on the profile page would be good. That would make it easier to make sure people can only delete the posts written by them.

**Comment by livvy10** [comment]
Yes I think on the profile page would be the best. But maybe we should only implement that at the end if we have time? Also it might be worthwhile to have a 'close post' functionality as well as delete, which stops people from commenting but can still be viewed. I'll add this to the relevant issue (future functionality)

**Comment by livvy10** [comment]
Delete post button on profile page is done. No time for 'close post' button, so closing issue.
