### ISSUE TITLE
Home page has no styling when first loaded.

### ISSUE THREAD

**Issue by Tay0710** [Tay0710/CITS3403_Project#32]
When the website opens on the home page it doesn't have any of it's normal styling.
Once you move to another page and back to the home page, the styling then shows.

Unsure why this is happening.

**Comment by livvy10** [comment]
hmmm.... not sure. Maybe when we tackle revisiting putting all our different css stylings together it will improve

**Comment by livvy10** [comment]
This issue has been resolved. Closing issue.
