### ISSUE TITLE
Basic HTML/CSS for Profile and createProfile pages

### ISSUE THREAD

**Issue by livvy10** [Tay0710/CITS3403_Project#4]
Purpose: A Profile page to display a user's profile information and an option to edit it. A createProfile page consisting of a form to take in user's details.

Not sure about the form elements for the create profile page:
- position: users need to select only one out of a list e.g. undergrad student, staff, future student etc. Currently it is with a select, but would input type="radio" be better?
- study: users need to be able to select from different majors/areas of study. Currently it is with a <select multiple> allowing them to select any number of pre-defined areas of study. But with this it is a long list and annoying to find your one, so I'm thinking either: 1. a text box and they put in their areas of study, separated by commas, or 2. only allow a limited number of areas of study (e.g. 2) and use datalist so they can search up pre-defined values or type in their own (the second area of study can be optional).

Any thoughts?

**Comment by Tay0710** [comment]
I think the radio buttons could look nice for the list, makes it super clear what the options are without scrolling.
A limited number of study areas will be easier to deal with initially in the database I believe, so I think we should start by using pre-defined values.

**Comment by livvy10** [comment]
Sounds good! I'll change it to radio buttons and change the study to just one value only (primary area of study) and only pre-defined values so we can compare easily. If we want to make it more complex (multiple areas of study, or user-defined values), we can add that later.
