### ISSUE TITLE
pop-up/newpage regarding profile

### ISSUE THREAD

**Issue by edenpowell** [Tay0710/CITS3403_Project#44]
do we want to direct the user to the homepage, or do a popup, or do an entire new page for once a profile has been created/deleted. Also consider changing username -- should go back to the profile page.

**Comment by livvy10** [comment]
For delete account it just goes back to the home page (no message displayed), they'll be able to tell by trying to log in and failing. 
For create profile, it currently goes to home page however I'll add a flash success message to indicate they created a profile and should now log in.

**Comment by livvy10** [comment]
Just added success msg when account created
