### ISSUE TITLE
Layout of the Forum Search Function

### ISSUE THREAD

**Issue by Tay0710** [Tay0710/CITS3403_Project#5]
We currently have two potential layouts for the transition into the forum page.
1. Hard-coded subjects topics which you can then click in to and find related posts.
2. A filter function which would show all posts related to the relevant subject/topic.

Not sure how we would look at combining these or what we should choose.

**Comment by NNN444TTT** [comment]
I think having the option of filter will be more user friendly rather than scrolling through a long list of topics, but the filter would still have the option to 'not filter', which would just show posts ordered by most recent?
