### ISSUE TITLE
Subjects/topics page 

### ISSUE THREAD

**Issue by NNN444TTT** [Tay0710/CITS3403_Project#6]
Not really sure what this page is for? Was the purpose just general information about courses/degrees? 
Ended up making it a search/filter page, so that you can pick from relevant 'tags' and find posts with these tags. Then the idea is that this page shows those posts with the filters and maybe provides the link to the original post?

**Comment by Tay0710** [comment]
I think this would be really good to merge with the forum page I was initially doing.
I'll look at altering the forum page I started into the create post page.

**Comment by NNN444TTT** [comment]
I agree, I think mine was starting to turn into the forum page. So the purpose of this page is now to 'house' the posts and where people go to view them. I like the look of the way you had the posts, so I'll incorporate that for the posts that would be shown under the filter.
